baseURL: ""
title: odirk.org
paginate: 6
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: odirk.org
    description: "odirk's blog"
    keywords: [Blog]
    author: gabriel
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "/static/favico.ico"
        favicon16x16: "/static/favicon-16x16.png"
        favicon32x32: "/static/favicon-32x32.png"
        apple_touch_icon: "/static/apple-touch-icon.png"
        safari_pinned_tab: "<link / abs url>"

    label:
        text: "Home"
        icon: /apple-touch-icon.png
        iconHeight: 35

    # profile-mode // deixar falso
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "odirk.org"
        Content: humor de baixa qualidade, opniões obtusas e receitas com preparo superior a 2 horas

    socialIcons:
        - name: twitter
          url: "https://twitter.com/odirk"
        - name: instagram
          url: "https://instagram.com/odirk"
        - name: lastfm
          url: "https://last.fm/user/GabrielDuro"
        - name: email
          url: "mailto:www@odirk.org"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "mailto://www@odirk.org?subject=Suggesting changes for "
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: search
          name: search
          url: /search/
          weight: 40
        - identifier: tags
          name: tags
          url: /tags/
          weight: 30
        - identifier: archive
          name: archive
          url: /archives/
          weight: 20
        - identifier: about
          name: about
          url: /about/
          weight: 10
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai